name: Docker

on:
  schedule:
    # Run every week on Monday at 2PM
    - cron: "0 14 * * 1"

  push:
    # Publish `develop` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: wappalyzer-api

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    services:
      redis:
        # We use nginx to test the extraction works as expected.
        image: nginx
        ports:
          - 3005:80

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run the wappalyzer image
        run: docker run -d -p 3000:3000 --name wappalyzer $IMAGE_NAME

      - name: Test the application
        run: |
          sleep 10
          OUTPUT=$(curl --fail --silent 'http://localhost:3000/extract?url=http://localhost:3005' 2>&1)
          EXIT_CODE=$?
          echo "Curl output: $OUTPUT"
          if [ $EXIT_CODE -eq 0 ]; then
            echo "Curl command succeeded."
          else
            echo "Curl command failed. Fetching docker logs..."
            docker logs wappalyzer
            exit 1
          fi

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "develop" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
